name: test
on: [push, pull_request, workflow_dispatch]
env: 
  CARGO_TERM_COLOR: always
  CI_JOB: test
jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: refreshenv && cargo test --all
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --all
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: .ci/general-jobs